#!/usr/bin/env bash
# appliance-smoke.sh — end-to-end test of the turnkey appliance without Linode.
# Starts applianced in file-fallback mode, logs in with the generated password,
# creates a migration via the console API, runs the agent against the embedded
# receiver, and drives the migration through to image_ready.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
PORT="${PORT:-18080}"
trap 'rm -rf "$WORK"; [ -n "${APP_PID:-}" ] && kill "$APP_PID" 2>/dev/null || true' EXIT

JAR="$WORK/cookies"
BASE="https://127.0.0.1:$PORT"
CACERT="$WORK/data/console.crt"   # self-signed console cert generated by applianced
api() { curl -fsS --cacert "$CACERT" -c "$JAR" -b "$JAR" "$@"; }

echo "== Build =="
( cd "$ROOT" && go build -o "$WORK/agent" ./cmd/agent && go build -o "$WORK/applianced" ./cmd/applianced )

echo "== Certs (SAN 127.0.0.1) =="
DAYS=30 "$ROOT/scripts/gen-certs.sh" "$WORK/certs" 127.0.0.1 >/dev/null

echo "== Start applianced (HTTPS console, file-fallback) =="
( cd "$WORK" && ./applianced -listen "127.0.0.1:$PORT" -data-dir "$WORK/data" -public-host 127.0.0.1 \
    -cert certs/receiver.crt -key certs/receiver.key -ca certs/ca.crt \
    -agent-cert certs/agent.crt -agent-key certs/agent.key -agent-binary "$WORK/agent" \
    >"$WORK/app.log" 2>&1 ) &
APP_PID=$!
for _ in $(seq 1 60); do grep -q "console on https" "$WORK/app.log" && [ -f "$CACERT" ] && break; sleep 0.1; done
grep -q "console on https" "$WORK/app.log" || { echo "applianced did not start"; cat "$WORK/app.log"; exit 1; }
echo "   console served over HTTPS; verifying against generated cert"

PW="$(cat "$WORK/data/initial-admin-password.txt")"
echo "   generated admin password: $PW"

echo "== Password recovery (-show-password reads it without touching the service) =="
SHOWPW="$(cd "$WORK" && ./applianced -data-dir "$WORK/data" -show-password)"
[ "$SHOWPW" = "$PW" ] || { echo "FAIL: -show-password returned '$SHOWPW', want '$PW'"; exit 1; }
echo "   OK: -show-password matches"

echo "== Login (over verified TLS) =="
api -X POST "$BASE/login" -H 'Content-Type: application/json' -d "{\"password\":\"$PW\"}" >/dev/null
echo "   OK (rejecting wrong password):"
if curl -fsS --cacert "$CACERT" -X POST "$BASE/login" -H 'Content-Type: application/json' -d '{"password":"wrong"}' >/dev/null 2>&1; then
  echo "   FAIL: wrong password accepted"; exit 1
fi
echo "   OK"

echo "== Create source disks: boot (16 MiB) + data (24 MiB) =="
dd if=/dev/urandom of="$WORK/sda.img" bs=1M count=16 status=none
dd if=/dev/urandom of="$WORK/sdb.img" bs=1M count=24 status=none
SZA=$(stat -c %s "$WORK/sda.img"); SZB=$(stat -c %s "$WORK/sdb.img")

echo "== Reject invalid source_ip =="
if api -X POST "$BASE/api/v1/migrations" -H 'Content-Type: application/json' \
  -d "{\"name\":\"badip\",\"source_ip\":\"1.2.3.4; rm -rf /\",\"devices\":[{\"device\":\"$WORK/sda.img\",\"size_bytes\":$SZA}]}" >/dev/null 2>&1; then
  echo "FAIL: invalid source_ip accepted"; exit 1
fi
echo "   OK: invalid source_ip rejected"

echo "== Create MULTI-DISK migration via console API =="
MIG=$(api -X POST "$BASE/api/v1/migrations" -H 'Content-Type: application/json' \
  -d "{\"name\":\"ec2-3disk\",\"source_hostname\":\"ec2\",\"source_ip\":\"127.0.0.1\",\"devices\":[{\"device\":\"$WORK/sda.img\",\"size_bytes\":$SZA},{\"device\":\"$WORK/sdb.img\",\"size_bytes\":$SZB}]}")
echo "$MIG" | jq -e '.migration.source_ip=="127.0.0.1"' >/dev/null || { echo "FAIL: source_ip not stored/echoed"; exit 1; }
MID=$(echo "$MIG" | jq -r '.migration.id')
NDISKS=$(echo "$MIG" | jq -r '.migration.disks | length')
PORT0=$(echo "$MIG" | jq -r '.migration.disks[0].receiver_port')
PORT1=$(echo "$MIG" | jq -r '.migration.disks[1].receiver_port')
ENROLL=$(echo "$MIG" | jq -r '.enroll_cmd')
echo "   migration id=$MID disks=$NDISKS ports=$PORT0,$PORT1"
[ "$NDISKS" = "2" ] && [ "$PORT0" -gt 0 ] && [ "$PORT1" -gt 0 ] && [ "$PORT0" != "$PORT1" ] \
  || { echo "FAIL: expected 2 disks with distinct ports"; exit 1; }
echo "$ENROLL" | grep -q 'https://' && echo "$ENROLL" | grep -q 'pinnedpubkey' \
  || { echo "FAIL: enrollment command not hardened: $ENROLL"; exit 1; }
echo "   OK: 2 disks, distinct ports, hardened enroll cmd"

echo "== Connection-test diagnostic (probe loopback) =="
CT=$(api -X POST "$BASE/api/v1/diagnostics/connection" -H 'Content-Type: application/json' -d '{"ip":"127.0.0.1"}')
echo "$CT" | jq -e '.ip=="127.0.0.1" and (.ports|type=="array") and (.ports|length>=2)' >/dev/null \
  || { echo "FAIL: conn-test shape unexpected: $CT"; exit 1; }
# Reject obviously bad input (command-injection guard / validation).
if api -X POST "$BASE/api/v1/diagnostics/connection" -H 'Content-Type: application/json' -d '{"ip":"1.2.3.4; rm -rf /"}' >/dev/null 2>&1; then
  echo "FAIL: conn-test accepted invalid host"; exit 1
fi
echo "   OK: probes returned, invalid host rejected"

echo "== Activity log records the creation event =="
EVENTS=$(api "$BASE/api/v1/migrations/$MID/events")
echo "$EVENTS" | jq -e 'type=="array" and length>=1' >/dev/null || { echo "FAIL: events endpoint empty: $EVENTS"; exit 1; }
echo "$EVENTS" | jq -e 'any(.[]; .message | contains("migration created"))' >/dev/null || { echo "FAIL: no creation event: $EVENTS"; exit 1; }
echo "   OK: /events returns the creation entry"

echo "== Verify the installer drives BOTH disks =="
TOKEN=$(echo "$ENROLL" | grep -o 'token=[a-f0-9]*' | cut -d= -f2)
SH=$(curl -fsS --cacert "$CACERT" "$BASE/install/agent.sh?token=$TOKEN")
[ "$(echo "$SH" | grep -c '^ExecStart=')" = "2" ] || { echo "FAIL: installer should have 2 ExecStart lines"; exit 1; }
echo "$SH" | grep -q 'systemctl stop vmrepl-agent' || { echo "FAIL: installer not re-run safe"; exit 1; }
echo "$SH" | grep -q ' -job ' || { echo "FAIL: installer must bake the enrollment job id into ExecStart"; exit 1; }
echo "   OK: 2 ExecStart lines, stop-before-replace, per-enrollment job id"

# Every session must present this enrollment's job id (token prefix) — the
# receiver refuses any other, so stale agents can't feed this migration.
JOB="${TOKEN:0:16}"
run_disk(){ local dev=$1 port=$2 man=$3; local ok=0; for _ in 1 2 3 4 5; do
  if "$WORK/agent" -device "$dev" -target "127.0.0.1:$port" -server-name 127.0.0.1 \
     -job "$JOB" -manifest "$man" -cert "$WORK/certs/agent.crt" -key "$WORK/certs/agent.key" -ca "$WORK/certs/ca.crt"; then ok=1; break; fi
  sleep 0.5; done; [ "$ok" = 1 ]; }

echo "== Identity guard: an agent from another enrollment is refused =="
# Simulates a stale agent from an old migration still firing at this port: valid
# certs, wrong job id. The receiver must reject it (and write nothing).
if "$WORK/agent" -device "$WORK/sda.img" -target "127.0.0.1:$PORT0" -server-name 127.0.0.1 \
   -job "stale-enrollment" -manifest "$WORK/rogue.cbt" -cert "$WORK/certs/agent.crt" -key "$WORK/certs/agent.key" -ca "$WORK/certs/ca.crt" 2>/dev/null; then
  echo "FAIL: a wrong-job (stale) agent session was accepted"; exit 1
fi
echo "   OK: wrong-job session rejected"

echo "== Gated start: a first agent pass only VALIDATES the connection (no data) =="
# Replication is not auto-started: the receiver acknowledges the agent and holds.
run_disk "$WORK/sda.img" "$PORT0" "$WORK/sda.cbt" || { echo "FAIL: boot disk connection check"; exit 1; }
run_disk "$WORK/sdb.img" "$PORT1" "$WORK/sdb.cbt" || { echo "FAIL: data disk connection check"; exit 1; }
V=$(api "$BASE/api/v1/migrations/$MID")
echo "$V" | jq -e '.agent_connected==true' >/dev/null || { echo "FAIL: agent_connected should be true after a connection check: $V"; exit 1; }
echo "$V" | jq -e '.replication_started==false' >/dev/null || { echo "FAIL: replication must NOT auto-start"; exit 1; }
echo "$V" | jq -e '.can_replicate==true' >/dev/null || { echo "FAIL: start should be enabled once the connection is validated"; exit 1; }
echo "$V" | jq -e '.migration.disks | all(.full_sync_done|not)' >/dev/null || { echo "FAIL: no disk should be baselined before replication is started"; exit 1; }
cmp -s "$WORK/sda.img" "$WORK/data/migration-$MID-disk0.img" 2>/dev/null && { echo "FAIL: data was applied before replication was started"; exit 1; }
echo "   OK: connection validated, replication held (no data written), start enabled"

echo "== Start replication (explicit operator gate) =="
api -X POST "$BASE/api/v1/migrations/$MID/replicate" >/dev/null || { echo "FAIL: /replicate rejected"; exit 1; }
V=$(api "$BASE/api/v1/migrations/$MID")
echo "$V" | jq -e '.replication_started==true' >/dev/null || { echo "FAIL: replication_started should be true after /replicate: $V"; exit 1; }
echo "   OK: replication started by operator"

echo "== Replicate each disk to its own port =="
run_disk "$WORK/sda.img" "$PORT0" "$WORK/sda.cbt" || { echo "FAIL: boot disk sync"; exit 1; }
run_disk "$WORK/sdb.img" "$PORT1" "$WORK/sdb.cbt" || { echo "FAIL: data disk sync"; exit 1; }

echo "== Verify BOTH replicated images match =="
cmp -s "$WORK/sda.img" "$WORK/data/migration-$MID-disk0.img" || { echo "FAIL: boot disk differs"; exit 1; }
cmp -s "$WORK/sdb.img" "$WORK/data/migration-$MID-disk1.img" || { echo "FAIL: data disk differs"; exit 1; }
echo "   OK: both disks byte-identical"

echo "== Check aggregate validations =="
V=$(api "$BASE/api/v1/migrations/$MID")
echo "$V" | jq -e '.migration.disks | all(.full_sync_done)' >/dev/null || { echo "FAIL: not all disks baselined"; exit 1; }
echo "$V" | jq -e '.can_migrate==true' >/dev/null || { echo "FAIL: validations not satisfied: $(echo "$V" | jq -c '.validations')"; exit 1; }
echo "$V" | jq -e '.migration.state=="ready"' >/dev/null || { echo "FAIL: status should flip to 'ready' once safe, got: $(echo "$V" | jq -r '.migration.state')"; exit 1; }
echo "   OK: all disks baselined, can_migrate=true, status shows ready"

echo "== Cutover is auto-enabled once baselined (no manual assessment) =="
echo "$V" | jq -e '.can_migrate==true' >/dev/null || { echo "FAIL: should be cutover-ready once baselined"; exit 1; }
echo "   OK: can_migrate true without an assessment step"

echo "== Pause replication: the gate holds, no data is applied =="
api -X POST "$BASE/api/v1/migrations/$MID/pause" >/dev/null || { echo "FAIL: /pause rejected"; exit 1; }
V=$(api "$BASE/api/v1/migrations/$MID")
echo "$V" | jq -e '.replication_active==false and .replication_paused==true' >/dev/null || { echo "FAIL: not paused: $V"; exit 1; }
# Change the source, then run the agent: while paused it must be HELD (target unchanged).
printf 'PAUSEDWRITE' | dd of="$WORK/sda.img" bs=1 seek=1048576 conv=notrunc status=none
run_disk "$WORK/sda.img" "$PORT0" "$WORK/sda.cbt" || { echo "FAIL: agent pass during pause errored (should hold cleanly)"; exit 1; }
cmp -s "$WORK/sda.img" "$WORK/data/migration-$MID-disk0.img" && { echo "FAIL: target changed while paused"; exit 1; }
echo "   OK: paused — agent held, the source change was not applied"

echo "== Resume replication: an incremental delta catches the target up =="
api -X POST "$BASE/api/v1/migrations/$MID/replicate" >/dev/null || { echo "FAIL: resume (/replicate) rejected"; exit 1; }
echo "$(api "$BASE/api/v1/migrations/$MID")" | jq -e '.replication_active==true' >/dev/null || { echo "FAIL: not active after resume"; exit 1; }
run_disk "$WORK/sda.img" "$PORT0" "$WORK/sda.cbt" || { echo "FAIL: delta pass after resume"; exit 1; }
cmp -s "$WORK/sda.img" "$WORK/data/migration-$MID-disk0.img" || { echo "FAIL: target not caught up after resume (delta not applied)"; exit 1; }
echo "   OK: resumed — delta applied (no full re-copy), target matches again"

echo "== Cutover (file-fallback finalize) =="
# skip_snapshot: the "source" here is static image files (never changing), so the
# replicated data is already consistent. Without this the cutover would block for
# minutes in quiesceForCutover waiting for a crash-consistent pass from the (one-shot,
# already-exited but still recently-seen) agent that never comes.
api -X POST "$BASE/api/v1/migrations/$MID/start" -H 'Content-Type: application/json' -d '{"skip_snapshot":true}' >/dev/null
for _ in $(seq 1 50); do
  STATE=$(api "$BASE/api/v1/migrations/$MID" | jq -r '.migration.state')
  [ "$STATE" = "image_ready" ] && break
  [ "$STATE" = "failed" ] && { echo "FAIL: $(api "$BASE/api/v1/migrations/$MID" | jq -r '.migration.last_error')"; exit 1; }
  sleep 0.2
done
[ "$STATE" = "image_ready" ] || { echo "FAIL: state=$STATE, want image_ready"; exit 1; }
echo "   OK: reached image_ready"

echo "== Uninstall command + script served =="
echo "$V" | jq -e '.uninstall_cmd | contains("/install/uninstall.sh")' >/dev/null || { echo "FAIL: uninstall_cmd missing"; exit 1; }
curl -fsS --cacert "$CACERT" "$BASE/install/uninstall.sh" | grep -q 'rm -rf /etc/vm-repl' || { echo "FAIL: uninstall script incomplete"; exit 1; }
echo "   OK"

echo "== Delete a migration removes BOTH disk files =="
M2=$(api -X POST "$BASE/api/v1/migrations" -H 'Content-Type: application/json' \
  -d "{\"name\":\"throwaway\",\"source_hostname\":\"x\",\"devices\":[{\"device\":\"$WORK/sda.img\",\"size_bytes\":$SZA},{\"device\":\"$WORK/sdb.img\",\"size_bytes\":$SZB}]}")
M2ID=$(echo "$M2" | jq -r '.migration.id')
# This migration has its OWN enrollment job id — sessions run with the previous
# migration's job would (correctly) be refused by the identity guard.
JOB="$(echo "$M2" | jq -r '.enroll_cmd' | grep -o 'token=[a-f0-9]*' | cut -d= -f2 | cut -c1-16)"
M2P0="$(echo "$M2" | jq -r '.migration.disks[0].receiver_port')"
M2P1="$(echo "$M2" | jq -r '.migration.disks[1].receiver_port')"
# Gated start: validate the connection on BOTH disks (held passes), then start
# replication and land one real pass so the fallback file exists (proving the
# delete below actually removes it, not that it never existed).
run_disk "$WORK/sda.img" "$M2P0" "$WORK/d2a.cbt" || { echo "FAIL: throwaway disk0 validation"; exit 1; }
run_disk "$WORK/sdb.img" "$M2P1" "$WORK/d2b.cbt" || { echo "FAIL: throwaway disk1 validation"; exit 1; }
api -X POST "$BASE/api/v1/migrations/$M2ID/replicate" >/dev/null
run_disk "$WORK/sda.img" "$M2P0" "$WORK/d2a.cbt" || { echo "FAIL: throwaway migration sync"; exit 1; }
[ -f "$WORK/data/migration-$M2ID-disk0.img" ] || { echo "FAIL: fallback file missing before delete"; exit 1; }
api -X DELETE "$BASE/api/v1/migrations/$M2ID" >/dev/null
COUNT=$(api "$BASE/api/v1/migrations" | jq '[.[] | select(.migration.id=='"$M2ID"')] | length')
[ "$COUNT" = "0" ] || { echo "FAIL: migration still present after delete"; exit 1; }
[ ! -f "$WORK/data/migration-$M2ID-disk0.img" ] || { echo "FAIL: disk0 file not cleaned up"; exit 1; }
echo "   OK: migration deleted (record + disk files)"

echo
echo "== Duplicate name rejected with friendly error =="
ERR=$(curl -sS --cacert "$CACERT" -b "$JAR" -X POST "$BASE/api/v1/migrations" -H 'Content-Type: application/json' \
  -d "{\"name\":\"ec2-3disk\",\"source_hostname\":\"dup.example\",\"devices\":[{\"device\":\"$WORK/sda.img\",\"size_bytes\":$SZA}]}")
echo "$ERR" | grep -qi 'already exists' || { echo "FAIL: expected friendly duplicate-name error, got: $ERR"; exit 1; }
echo "   OK: friendly duplicate-name error"

echo
echo "APPLIANCE SMOKE PASSED"
